# Generated by Django 4.1.2 on 2022-11-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
    ]
