# Generated by Django 4.1.2 on 2022-11-01 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumURI', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('artist', models.TextField(verbose_name='Artist')),
                ('release_date', models.DateField(null=True)),
                ('cover_art', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songURI', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField(null=True)),
                ('song_preview', models.TextField()),
                ('track_number', models.IntegerField()),
                ('artists', models.TextField(null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('songs', models.ManyToManyField(blank=True, to='api.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
